"""Seed suppliers data from biomedical suppliers master list"""

import sys
sys.path.insert(0, '.')

from app.core.database import SessionLocal, engine, Base
from app.models.models import Supplier

# Create tables
Base.metadata.create_all(bind=engine)

# Supplier data from biomedical_suppliers_master_150.xlsx
SUPPLIERS_DATA = [
    {"supplier_id": "SUP-001", "category": "Chemicals, Reagents & Life Science Consumables", "subcategory": "Integrated life science supplier", "company": "Thermo Fisher Scientific", "description": "Full-spectrum reagents, kits, and instruments", "market_segment": "Both", "research_use": True, "clinical_use": True, "primary_offerings": "Reagents; kits; instruments; consumables", "common_applications": "PCR/qPCR, NGS prep, cell biology, proteomics", "ai_recommendation_tags": "PCR; NGS; cell culture; instruments", "workflow_examples": "Sample prep, PCR setup, sequencing workflows", "procurement_priority": "High", "approval_status": "Review", "is_preferred": True, "website": "https://www.thermofisher.com", "internal_notes": "End-to-end ecosystem leader", "budget_tier": "Premium", "country_region": "Global"},
    {"supplier_id": "SUP-002", "category": "Chemicals, Reagents & Life Science Consumables", "subcategory": "Biochemicals and solvents", "company": "Merck KGaA (MilliporeSigma)", "description": "Biochemicals, solvents, and reagents", "market_segment": "Both", "research_use": True, "clinical_use": True, "primary_offerings": "Chemicals; reagents; lab essentials", "common_applications": "Chemistry, molecular biology, analytical workflows", "ai_recommendation_tags": "chemicals; solvents; reagents; analytics", "workflow_examples": "Buffer prep, chemical synthesis, assay support", "procurement_priority": "High", "approval_status": "Review", "is_preferred": True, "website": "https://www.sigmaaldrich.com", "internal_notes": "Strong cross-category supplier", "budget_tier": "Premium", "country_region": "Global"},
    {"supplier_id": "SUP-003", "category": "Chemicals, Reagents & Life Science Consumables", "subcategory": "Molecular biology reagents", "company": "Bio-Rad Laboratories", "description": "PCR, electrophoresis, and reagents", "market_segment": "Both", "research_use": True, "clinical_use": True, "primary_offerings": "PCR reagents; electrophoresis; imaging", "common_applications": "PCR/qPCR, gel electrophoresis, protein analysis", "ai_recommendation_tags": "PCR; electrophoresis; western blot", "workflow_examples": "PCR amplification, gels, blotting", "procurement_priority": "High", "approval_status": "Review", "is_preferred": False, "website": "https://www.bio-rad.com", "internal_notes": "Widely used in research and clinical labs", "budget_tier": "Mid-market", "country_region": "Global"},
    {"supplier_id": "SUP-004", "category": "Chemicals, Reagents & Life Science Consumables", "subcategory": "Omics and analytical reagents", "company": "Agilent Technologies", "description": "Genomics and proteomics reagents", "market_segment": "Both", "research_use": True, "clinical_use": True, "primary_offerings": "Omics reagents; analytical systems", "common_applications": "Genomics, proteomics, chromatography, mass spec", "ai_recommendation_tags": "genomics; proteomics; LC-MS", "workflow_examples": "NGS QC, sample analysis, analytical chemistry", "procurement_priority": "High", "approval_status": "Review", "is_preferred": False, "website": "https://www.agilent.com", "internal_notes": "Strong in analytics and omics", "budget_tier": "Premium", "country_region": "Global"},
    {"supplier_id": "SUP-005", "category": "Chemicals, Reagents & Life Science Consumables", "subcategory": "Diagnostics and reagent portfolio", "company": "Danaher (Cytiva, Beckman Coulter)", "description": "Diagnostics and reagents across multiple platforms", "market_segment": "Both", "research_use": True, "clinical_use": True, "primary_offerings": "Bioprocessing; diagnostics; instruments", "common_applications": "Cell biology, clinical diagnostics, bioprocessing", "ai_recommendation_tags": "diagnostics; bioprocessing; instruments", "workflow_examples": "Cell culture, clinical chemistry, bioprocess workflows", "procurement_priority": "High", "approval_status": "Review", "is_preferred": True, "website": "https://www.danaher.com", "internal_notes": "End-to-end ecosystem leader", "budget_tier": "Premium", "country_region": "Global"},
    {"supplier_id": "SUP-006", "category": "Chemicals, Reagents & Life Science Consumables", "subcategory": "Sample preparation", "company": "QIAGEN", "description": "Sample preparation and molecular assays", "market_segment": "Both", "research_use": True, "clinical_use": True, "primary_offerings": "Extraction kits; PCR assays; automation", "common_applications": "DNA/RNA extraction, qPCR, translational research", "ai_recommendation_tags": "sample prep; qPCR; extraction", "workflow_examples": "Nucleic acid extraction, assay setup", "procurement_priority": "High", "approval_status": "Review", "is_preferred": True, "website": "https://www.qiagen.com", "internal_notes": "Very strong for molecular workflows", "budget_tier": "Premium", "country_region": "Global"},
    {"supplier_id": "SUP-007", "category": "Chemicals, Reagents & Life Science Consumables", "subcategory": "Enzymes and cloning", "company": "New England Biolabs", "description": "Enzymes and cloning reagents", "market_segment": "Research only", "research_use": True, "clinical_use": False, "primary_offerings": "Restriction enzymes; polymerases; cloning kits", "common_applications": "Cloning, PCR, genome editing support", "ai_recommendation_tags": "enzymes; cloning; CRISPR; PCR", "workflow_examples": "Plasmid assembly, PCR optimization, cloning", "procurement_priority": "High", "approval_status": "Review", "is_preferred": True, "website": "https://www.neb.com", "internal_notes": "Specialized leader for enzymes", "budget_tier": "Mid-market", "country_region": "Global"},
    {"supplier_id": "SUP-008", "category": "Chemicals, Reagents & Life Science Consumables", "subcategory": "Assay reagents", "company": "Promega", "description": "Assays and luciferase systems", "market_segment": "Research only", "research_use": True, "clinical_use": False, "primary_offerings": "Assay kits; reporter systems; enzymes", "common_applications": "Cell-based assays, reporter assays, molecular biology", "ai_recommendation_tags": "assays; luciferase; cell biology", "workflow_examples": "Reporter assays, viability testing, molecular assays", "procurement_priority": "Medium", "approval_status": "Review", "is_preferred": False, "website": "https://www.promega.com", "internal_notes": "Strong in assay development", "budget_tier": "Mid-market", "country_region": "Global"},
    {"supplier_id": "SUP-009", "category": "Chemicals, Reagents & Life Science Consumables", "subcategory": "PCR and gene expression", "company": "Takara Bio", "description": "PCR and gene expression reagents", "market_segment": "Research only", "research_use": True, "clinical_use": False, "primary_offerings": "PCR mixes; RT-PCR; expression reagents", "common_applications": "Gene expression, cDNA synthesis, cloning", "ai_recommendation_tags": "PCR; RT-PCR; gene expression", "workflow_examples": "Reverse transcription, qPCR, transcript analysis", "procurement_priority": "Medium", "approval_status": "Review", "is_preferred": False, "website": "https://www.takarabio.com", "internal_notes": "Useful for expression workflows", "budget_tier": "Mid-market", "country_region": "Global"},
    {"supplier_id": "SUP-010", "category": "Chemicals, Reagents & Life Science Consumables", "subcategory": "Cell culture reagents", "company": "Lonza Group", "description": "Cell culture reagents and media", "market_segment": "Both", "research_use": True, "clinical_use": True, "primary_offerings": "Media; transfection; cell therapy support", "common_applications": "Cell culture, primary cells, translational work", "ai_recommendation_tags": "cell culture; media; transfection", "workflow_examples": "Cell expansion, transfection, culture maintenance", "procurement_priority": "High", "approval_status": "Review", "is_preferred": False, "website": "https://www.lonza.com", "internal_notes": "Strong in cell culture and bioprocess", "budget_tier": "Mid-market", "country_region": "Global"},
    {"supplier_id": "SUP-011", "category": "Antibodies, Proteins & Immunoassays", "subcategory": "Research antibodies", "company": "Abcam", "description": "Broad antibody portfolio", "market_segment": "Research only", "research_use": True, "clinical_use": False, "primary_offerings": "Primary antibodies; recombinant antibodies; kits", "common_applications": "Western blot, IHC, IF, ELISA", "ai_recommendation_tags": "antibodies; IHC; IF; western blot", "workflow_examples": "Target validation, staining, immunoassays", "procurement_priority": "High", "approval_status": "Review", "is_preferred": True, "website": "https://www.abcam.com", "internal_notes": "Specialized leader in antibodies", "budget_tier": "Mid-market", "country_region": "Global"},
    {"supplier_id": "SUP-012", "category": "Antibodies, Proteins & Immunoassays", "subcategory": "Signaling antibodies", "company": "Cell Signaling Technology", "description": "High-quality signaling antibodies", "market_segment": "Research only", "research_use": True, "clinical_use": False, "primary_offerings": "Pathway antibodies; validation data", "common_applications": "Western blot, signaling studies, IF, IHC", "ai_recommendation_tags": "signaling antibodies; WB; IHC", "workflow_examples": "Pathway analysis, phospho-protein studies", "procurement_priority": "High", "approval_status": "Review", "is_preferred": True, "website": "https://www.cellsignal.com", "internal_notes": "Specialized leader for signaling biology", "budget_tier": "Mid-market", "country_region": "Global"},
    {"supplier_id": "SUP-013", "category": "Antibodies, Proteins & Immunoassays", "subcategory": "Antibodies and RNAi", "company": "Santa Cruz Biotechnology", "description": "Antibodies and siRNA", "market_segment": "Research only", "research_use": True, "clinical_use": False, "primary_offerings": "Antibodies; siRNA; proteins", "common_applications": "Knockdown studies, WB, IF, IHC", "ai_recommendation_tags": "siRNA; antibodies; IF", "workflow_examples": "Gene knockdown support, antibody screening", "procurement_priority": "Medium", "approval_status": "Review", "is_preferred": False, "website": "https://www.scbt.com", "internal_notes": "Broad catalog", "budget_tier": "Mid-market", "country_region": "Global"},
    {"supplier_id": "SUP-014", "category": "Antibodies, Proteins & Immunoassays", "subcategory": "Flow cytometry reagents", "company": "BioLegend", "description": "Flow cytometry antibodies", "market_segment": "Research only", "research_use": True, "clinical_use": False, "primary_offerings": "Flow antibodies; ELISA kits; cytokines", "common_applications": "Flow cytometry, immunophenotyping, ELISA", "ai_recommendation_tags": "flow cytometry; immunology; ELISA", "workflow_examples": "Panel design, immune profiling", "procurement_priority": "High", "approval_status": "Review", "is_preferred": True, "website": "https://www.biolegend.com", "internal_notes": "Specialized leader for flow", "budget_tier": "Mid-market", "country_region": "Global"},
    {"supplier_id": "SUP-015", "category": "Antibodies, Proteins & Immunoassays", "subcategory": "Cytokines and ELISA", "company": "R&D Systems (Bio-Techne)", "description": "ELISA kits and cytokines", "market_segment": "Both", "research_use": True, "clinical_use": True, "primary_offerings": "ELISA kits; proteins; cytokines", "common_applications": "Biomarker analysis, immunology, translational studies", "ai_recommendation_tags": "ELISA; cytokines; biomarkers", "workflow_examples": "Protein quantification, cytokine profiling", "procurement_priority": "High", "approval_status": "Review", "is_preferred": True, "website": "https://www.bio-techne.com", "internal_notes": "Strong in proteins and ELISA", "budget_tier": "Mid-market", "country_region": "Global"},
    {"supplier_id": "SUP-016", "category": "Antibodies, Proteins & Immunoassays", "subcategory": "Antibodies and recombinant proteins", "company": "Proteintech", "description": "Antibodies and recombinant proteins", "market_segment": "Research only", "research_use": True, "clinical_use": False, "primary_offerings": "Primary antibodies; recombinant proteins", "common_applications": "WB, IF, IHC, target validation", "ai_recommendation_tags": "antibodies; recombinant proteins; IHC", "workflow_examples": "Antibody screening, protein studies", "procurement_priority": "Medium", "approval_status": "Review", "is_preferred": False, "website": "https://www.ptglab.com", "internal_notes": "Reliable antibody supplier", "budget_tier": "Mid-market", "country_region": "Global"},
    {"supplier_id": "SUP-017", "category": "Antibodies, Proteins & Immunoassays", "subcategory": "Custom biologics", "company": "GenScript", "description": "Custom proteins and antibodies", "market_segment": "Both", "research_use": True, "clinical_use": True, "primary_offerings": "Custom gene synthesis; proteins; antibodies", "common_applications": "Protein expression, antibody development, assay support", "ai_recommendation_tags": "custom proteins; antibodies; synthesis", "workflow_examples": "Custom reagent development, validation", "procurement_priority": "High", "approval_status": "Review", "is_preferred": False, "website": "https://www.genscript.com", "internal_notes": "Useful for custom services", "budget_tier": "Mid-market", "country_region": "Global"},
    {"supplier_id": "SUP-018", "category": "Antibodies, Proteins & Immunoassays", "subcategory": "Monoclonal antibodies", "company": "Abnova", "description": "Monoclonal antibodies", "market_segment": "Research only", "research_use": True, "clinical_use": False, "primary_offerings": "Monoclonal antibodies; proteins", "common_applications": "Target validation, WB, IF, ELISA", "ai_recommendation_tags": "monoclonal antibodies; ELISA", "workflow_examples": "Antibody sourcing, assay development", "procurement_priority": "Medium", "approval_status": "Review", "is_preferred": False, "website": "https://www.abnova.com", "internal_notes": "Specialty antibody catalog", "budget_tier": "Mid-market", "country_region": "Global"},
    {"supplier_id": "SUP-019", "category": "Antibodies, Proteins & Immunoassays", "subcategory": "Antibodies and clones", "company": "OriGene Technologies", "description": "Antibodies and cDNA clones", "market_segment": "Research only", "research_use": True, "clinical_use": False, "primary_offerings": "Antibodies; cDNA clones; expression tools", "common_applications": "Gene expression studies, validation, WB", "ai_recommendation_tags": "cDNA clones; antibodies; expression", "workflow_examples": "Clone sourcing, validation workflows", "procurement_priority": "Medium", "approval_status": "Review", "is_preferred": False, "website": "https://www.origene.com", "internal_notes": "Strong gene-to-protein catalog", "budget_tier": "Mid-market", "country_region": "Global"},
    {"supplier_id": "SUP-020", "category": "Antibodies, Proteins & Immunoassays", "subcategory": "Branded antibody portfolio", "company": "Thermo Fisher Antibodies", "description": "Large antibody portfolio", "market_segment": "Both", "research_use": True, "clinical_use": True, "primary_offerings": "Primary/secondary antibodies; assay reagents", "common_applications": "WB, IF, IHC, ELISA, multiplex assays", "ai_recommendation_tags": "antibodies; ELISA; multiplex", "workflow_examples": "Immunodetection, assay buildout", "procurement_priority": "High", "approval_status": "Review", "is_preferred": True, "website": "https://www.thermofisher.com/antibody", "internal_notes": "Large integrated portfolio", "budget_tier": "Mid-market", "country_region": "Global"},
    {"supplier_id": "SUP-021", "category": "Assays, Kits & Molecular Diagnostics", "subcategory": "Clinical diagnostics", "company": "Roche Diagnostics", "description": "Clinical assays", "market_segment": "Clinical/Hospital only", "research_use": False, "clinical_use": True, "primary_offerings": "Clinical analyzers; molecular tests; assays", "common_applications": "Clinical chemistry, oncology diagnostics, pathology", "ai_recommendation_tags": "clinical diagnostics; oncology; assays", "workflow_examples": "Diagnostic testing, hospital lab workflows", "procurement_priority": "High", "approval_status": "Review", "is_preferred": True, "website": "https://diagnostics.roche.com", "internal_notes": "Specialized leader in clinical diagnostics", "budget_tier": "Premium", "country_region": "Global"},
    {"supplier_id": "SUP-022", "category": "Assays, Kits & Molecular Diagnostics", "subcategory": "Clinical assays", "company": "Abbott Laboratories", "description": "Diagnostics and assays", "market_segment": "Clinical/Hospital only", "research_use": False, "clinical_use": True, "primary_offerings": "Diagnostic platforms; immunoassays; molecular tests", "common_applications": "Hospital labs, screening, infectious disease", "ai_recommendation_tags": "clinical assays; hospital lab; screening", "workflow_examples": "Routine diagnostics, screening panels", "procurement_priority": "High", "approval_status": "Review", "is_preferred": True, "website": "https://www.abbott.com", "internal_notes": "Specialized leader in diagnostics", "budget_tier": "Premium", "country_region": "Global"},
    {"supplier_id": "SUP-023", "category": "Assays, Kits & Molecular Diagnostics", "subcategory": "Microbiology diagnostics", "company": "bioMerieux", "description": "Microbiology diagnostics", "market_segment": "Clinical/Hospital only", "research_use": False, "clinical_use": True, "primary_offerings": "Microbiology ID/AST; PCR diagnostics", "common_applications": "Clinical microbiology, infectious disease testing", "ai_recommendation_tags": "microbiology; diagnostics; PCR", "workflow_examples": "Culture ID, pathogen detection", "procurement_priority": "High", "approval_status": "Review", "is_preferred": False, "website": "https://www.biomerieux.com", "internal_notes": "Strong in microbiology", "budget_tier": "Mid-market", "country_region": "Global"},
    {"supplier_id": "SUP-024", "category": "Assays, Kits & Molecular Diagnostics", "subcategory": "Hospital diagnostics", "company": "Siemens Healthineers", "description": "Clinical diagnostics", "market_segment": "Clinical/Hospital only", "research_use": False, "clinical_use": True, "primary_offerings": "Clinical chemistry; immunoassay; imaging", "common_applications": "Hospital diagnostics, automation, analyzers", "ai_recommendation_tags": "clinical chemistry; analyzers; hospital", "workflow_examples": "Routine hospital testing", "procurement_priority": "High", "approval_status": "Review", "is_preferred": False, "website": "https://www.siemens-healthineers.com", "internal_notes": "Major hospital platform", "budget_tier": "Premium", "country_region": "Global"},
    {"supplier_id": "SUP-025", "category": "Assays, Kits & Molecular Diagnostics", "subcategory": "Imaging and assays", "company": "PerkinElmer (Revvity)", "description": "Imaging and assay solutions", "market_segment": "Both", "research_use": True, "clinical_use": True, "primary_offerings": "Imaging systems; assay kits; screening tools", "common_applications": "Cell imaging, screening, diagnostics", "ai_recommendation_tags": "imaging; screening; assays", "workflow_examples": "High-content screening, translational assays", "procurement_priority": "High", "approval_status": "Review", "is_preferred": False, "website": "https://www.revvity.com", "internal_notes": "Strong in imaging plus assays", "budget_tier": "Mid-market", "country_region": "Global"},
    {"supplier_id": "SUP-026", "category": "Assays, Kits & Molecular Diagnostics", "subcategory": "NGS platforms and kits", "company": "Illumina", "description": "NGS kits and sequencing platforms", "market_segment": "Both", "research_use": True, "clinical_use": True, "primary_offerings": "Sequencers; library prep; bioinformatics", "common_applications": "Whole-genome, exome, targeted sequencing", "ai_recommendation_tags": "NGS; sequencing; library prep", "workflow_examples": "WGS, targeted panels, sequencing QC", "procurement_priority": "High", "approval_status": "Review", "is_preferred": True, "website": "https://www.illumina.com", "internal_notes": "Specialized leader in NGS", "budget_tier": "Premium", "country_region": "Global"},
    {"supplier_id": "SUP-027", "category": "Assays, Kits & Molecular Diagnostics", "subcategory": "qPCR assay design", "company": "LGC Biosearch Technologies", "description": "qPCR assays", "market_segment": "Research only", "research_use": True, "clinical_use": False, "primary_offerings": "Oligos; probes; qPCR design", "common_applications": "qPCR, genotyping, molecular detection", "ai_recommendation_tags": "qPCR; probes; oligos", "workflow_examples": "Assay design, qPCR testing", "procurement_priority": "Medium", "approval_status": "Review", "is_preferred": False, "website": "https://www.biosearchtech.com", "internal_notes": "Useful for custom qPCR", "budget_tier": "Mid-market", "country_region": "Global"},
    {"supplier_id": "SUP-028", "category": "Assays, Kits & Molecular Diagnostics", "subcategory": "PCR enzymes", "company": "Toyobo", "description": "Enzymes and PCR kits", "market_segment": "Research only", "research_use": True, "clinical_use": False, "primary_offerings": "Polymerases; PCR kits; RT reagents", "common_applications": "PCR, RT-PCR, cloning support", "ai_recommendation_tags": "PCR; enzymes; RT-PCR", "workflow_examples": "Amplification, reverse transcription", "procurement_priority": "Medium", "approval_status": "Review", "is_preferred": False, "website": "https://www.toyobo-global.com", "internal_notes": "Useful for molecular biology", "budget_tier": "Mid-market", "country_region": "Global"},
    {"supplier_id": "SUP-029", "category": "Assays, Kits & Molecular Diagnostics", "subcategory": "Testing services and kits", "company": "Eurofins Scientific", "description": "Testing kits and services", "market_segment": "Both", "research_use": True, "clinical_use": True, "primary_offerings": "Testing services; specialty assays; QA", "common_applications": "Food, pharma, clinical and research testing", "ai_recommendation_tags": "testing services; QA; assays", "workflow_examples": "Outsourced testing, assay support", "procurement_priority": "Medium", "approval_status": "Review", "is_preferred": False, "website": "https://www.eurofins.com", "internal_notes": "Service-heavy partner", "budget_tier": "Mid-market", "country_region": "Global"},
    {"supplier_id": "SUP-030", "category": "Assays, Kits & Molecular Diagnostics", "subcategory": "Diagnostic reagents", "company": "Meridian Bioscience", "description": "Diagnostic reagents", "market_segment": "Both", "research_use": True, "clinical_use": True, "primary_offerings": "PCR/qPCR reagents; immunoassay materials", "common_applications": "Molecular diagnostics, assay manufacturing support", "ai_recommendation_tags": "diagnostic reagents; qPCR", "workflow_examples": "Assay development, diagnostic workflows", "procurement_priority": "Medium", "approval_status": "Review", "is_preferred": False, "website": "https://www.meridianbioscience.com", "internal_notes": "Useful for diagnostic development", "budget_tier": "Mid-market", "country_region": "Global"},
    {"supplier_id": "SUP-031", "category": "Instruments & Laboratory Equipment", "subcategory": "Imaging and lab systems", "company": "GE HealthCare", "description": "Imaging and laboratory systems", "market_segment": "Both", "research_use": True, "clinical_use": True, "primary_offerings": "Imaging platforms; lab systems", "common_applications": "Imaging, diagnostics, translational medicine", "ai_recommendation_tags": "imaging; hospital systems; lab systems", "workflow_examples": "Imaging workflows, translational labs", "procurement_priority": "High", "approval_status": "Review", "is_preferred": False, "website": "https://www.gehealthcare.com", "internal_notes": "Major healthcare platform", "budget_tier": "Premium", "country_region": "Global"},
    {"supplier_id": "SUP-032", "category": "Instruments & Laboratory Equipment", "subcategory": "Bioprocessing systems", "company": "Sartorius", "description": "Bioprocessing and instruments", "market_segment": "Both", "research_use": True, "clinical_use": True, "primary_offerings": "Bioprocess systems; balances; cell analysis", "common_applications": "Bioprocessing, cell culture, QC", "ai_recommendation_tags": "bioprocessing; cell analysis; balances", "workflow_examples": "Cell manufacturing, QC, upstream workflows", "procurement_priority": "High", "approval_status": "Review", "is_preferred": False, "website": "https://www.sartorius.com", "internal_notes": "Strong in bioprocess and lab equipment", "budget_tier": "Premium", "country_region": "Global"},
    {"supplier_id": "SUP-033", "category": "Instruments & Laboratory Equipment", "subcategory": "Chromatography and mass spectrometry", "company": "Waters Corporation", "description": "Mass spectrometry and chromatography", "market_segment": "Both", "research_use": True, "clinical_use": True, "primary_offerings": "LC; LC-MS; informatics", "common_applications": "Analytical chemistry, metabolomics, QA/QC", "ai_recommendation_tags": "mass spectrometry; chromatography; LC-MS", "workflow_examples": "Analytical profiling, compound analysis", "procurement_priority": "High", "approval_status": "Review", "is_preferred": False, "website": "https://www.waters.com", "internal_notes": "Specialized analytical leader", "budget_tier": "Premium", "country_region": "Global"},
    {"supplier_id": "SUP-034", "category": "Instruments & Laboratory Equipment", "subcategory": "Clinical analyzers", "company": "Beckman Coulter", "description": "Clinical analyzers", "market_segment": "Clinical/Hospital only", "research_use": False, "clinical_use": True, "primary_offerings": "Hematology; clinical chemistry; flow cytometry", "common_applications": "Hospital labs, routine diagnostics, flow", "ai_recommendation_tags": "hematology; clinical chemistry; flow", "workflow_examples": "Routine hospital testing, flow cytometry", "procurement_priority": "High", "approval_status": "Review", "is_preferred": False, "website": "https://www.beckmancoulter.com", "internal_notes": "Part of Danaher ecosystem", "budget_tier": "Premium", "country_region": "Global"},
    {"supplier_id": "SUP-035", "category": "Instruments & Laboratory Equipment", "subcategory": "Flow cytometers", "company": "BD Biosciences", "description": "Flow cytometry instruments", "market_segment": "Both", "research_use": True, "clinical_use": True, "primary_offerings": "Flow cytometers; cell sorters; reagents", "common_applications": "Flow cytometry, cell sorting, immunology", "ai_recommendation_tags": "flow cytometry; cell sorting; BD", "workflow_examples": "Immune profiling, cell isolation", "procurement_priority": "High", "approval_status": "Review", "is_preferred": True, "website": "https://www.bdbiosciences.com", "internal_notes": "Leading flow platform", "budget_tier": "Premium", "country_region": "Global"},
    {"supplier_id": "SUP-036", "category": "Instruments & Laboratory Equipment", "subcategory": "Microscopy", "company": "Zeiss", "description": "Microscopy systems", "market_segment": "Both", "research_use": True, "clinical_use": True, "primary_offerings": "Microscopes; imaging systems; software", "common_applications": "Cell imaging, histology, materials science", "ai_recommendation_tags": "microscopy; imaging; confocal", "workflow_examples": "Cell imaging, tissue analysis", "procurement_priority": "High", "approval_status": "Review", "is_preferred": True, "website": "https://www.zeiss.com", "internal_notes": "Premium microscopy leader", "budget_tier": "Premium", "country_region": "Global"},
    {"supplier_id": "SUP-037", "category": "Instruments & Laboratory Equipment", "subcategory": "Centrifuges and automation", "company": "Eppendorf", "description": "Lab equipment and automation", "market_segment": "Both", "research_use": True, "clinical_use": True, "primary_offerings": "Centrifuges; pipettes; liquid handling", "common_applications": "Sample processing, cell culture, automation", "ai_recommendation_tags": "centrifuges; pipettes; automation", "workflow_examples": "Sample prep, liquid handling", "procurement_priority": "High", "approval_status": "Review", "is_preferred": True, "website": "https://www.eppendorf.com", "internal_notes": "Lab essentials leader", "budget_tier": "Mid-market", "country_region": "Global"},
    {"supplier_id": "SUP-038", "category": "Instruments & Laboratory Equipment", "subcategory": "Spectroscopy", "company": "Bruker", "description": "Spectroscopy and analytical instruments", "market_segment": "Both", "research_use": True, "clinical_use": True, "primary_offerings": "NMR; mass spec; spectroscopy", "common_applications": "Structural analysis, metabolomics, proteomics", "ai_recommendation_tags": "NMR; mass spec; spectroscopy", "workflow_examples": "Structural biology, compound ID", "procurement_priority": "High", "approval_status": "Review", "is_preferred": False, "website": "https://www.bruker.com", "internal_notes": "Specialized analytical leader", "budget_tier": "Premium", "country_region": "Global"},
    {"supplier_id": "SUP-039", "category": "Instruments & Laboratory Equipment", "subcategory": "Plate readers", "company": "Molecular Devices", "description": "Plate readers and imaging", "market_segment": "Both", "research_use": True, "clinical_use": True, "primary_offerings": "Plate readers; imaging systems; software", "common_applications": "HTS, cell assays, absorbance/fluorescence", "ai_recommendation_tags": "plate readers; HTS; cell assays", "workflow_examples": "Drug screening, assay development", "procurement_priority": "High", "approval_status": "Review", "is_preferred": False, "website": "https://www.moleculardevices.com", "internal_notes": "Strong in plate readers", "budget_tier": "Mid-market", "country_region": "Global"},
    {"supplier_id": "SUP-040", "category": "Instruments & Laboratory Equipment", "subcategory": "PCR instruments", "company": "Applied Biosystems (Thermo)", "description": "PCR and sequencing instruments", "market_segment": "Both", "research_use": True, "clinical_use": True, "primary_offerings": "Real-time PCR; Sanger sequencing", "common_applications": "qPCR, genotyping, Sanger sequencing", "ai_recommendation_tags": "qPCR; Sanger; genotyping", "workflow_examples": "Gene expression, mutation detection", "procurement_priority": "High", "approval_status": "Review", "is_preferred": True, "website": "https://www.thermofisher.com/applied-biosystems", "internal_notes": "Gold standard for qPCR", "budget_tier": "Premium", "country_region": "Global"},
    {"supplier_id": "SUP-041", "category": "Clinical, Hospital & Lab Supply Companies", "subcategory": "Lab consumables", "company": "VWR (Avantor)", "description": "Lab supplies and chemicals", "market_segment": "Both", "research_use": True, "clinical_use": True, "primary_offerings": "Consumables; chemicals; equipment", "common_applications": "General lab supply, chemical sourcing", "ai_recommendation_tags": "lab supplies; consumables; chemicals", "workflow_examples": "Lab procurement, consumables sourcing", "procurement_priority": "High", "approval_status": "Review", "is_preferred": True, "website": "https://www.avantorsciences.com", "internal_notes": "Major distributor", "budget_tier": "Mid-market", "country_region": "Global"},
    {"supplier_id": "SUP-042", "category": "Clinical, Hospital & Lab Supply Companies", "subcategory": "Lab distribution", "company": "Fisher Scientific", "description": "Lab supplies distribution", "market_segment": "Both", "research_use": True, "clinical_use": True, "primary_offerings": "Lab supplies; equipment; reagents", "common_applications": "Lab procurement, equipment sourcing", "ai_recommendation_tags": "lab supplies; distribution; equipment", "workflow_examples": "One-stop lab procurement", "procurement_priority": "High", "approval_status": "Review", "is_preferred": True, "website": "https://www.fishersci.com", "internal_notes": "Part of Thermo Fisher", "budget_tier": "Mid-market", "country_region": "Global"},
    {"supplier_id": "SUP-043", "category": "Clinical, Hospital & Lab Supply Companies", "subcategory": "Plasticware", "company": "Corning Life Sciences", "description": "Plasticware and cell culture vessels", "market_segment": "Both", "research_use": True, "clinical_use": True, "primary_offerings": "Cell culture vessels; plasticware; glass", "common_applications": "Cell culture, sample storage, labware", "ai_recommendation_tags": "plasticware; cell culture vessels; labware", "workflow_examples": "Cell culture setup, sample handling", "procurement_priority": "High", "approval_status": "Review", "is_preferred": True, "website": "https://www.corning.com/lifesciences", "internal_notes": "Lab essentials leader", "budget_tier": "Mid-market", "country_region": "Global"},
    {"supplier_id": "SUP-044", "category": "Clinical, Hospital & Lab Supply Companies", "subcategory": "Filtration and purification", "company": "Pall Corporation", "description": "Filtration and separation", "market_segment": "Both", "research_use": True, "clinical_use": True, "primary_offerings": "Filtration; purification; bioprocess", "common_applications": "Bioprocessing, filtration, purification", "ai_recommendation_tags": "filtration; purification; bioprocess", "workflow_examples": "Media filtration, protein purification", "procurement_priority": "Medium", "approval_status": "Review", "is_preferred": False, "website": "https://www.pall.com", "internal_notes": "Strong in filtration", "budget_tier": "Mid-market", "country_region": "Global"},
    {"supplier_id": "SUP-045", "category": "Clinical, Hospital & Lab Supply Companies", "subcategory": "Cryogenic storage", "company": "Thermo Fisher Cryogenic", "description": "Cryogenic storage systems", "market_segment": "Both", "research_use": True, "clinical_use": True, "primary_offerings": "Freezers; cryogenic storage; cold chain", "common_applications": "Sample storage, biobanking, cold chain", "ai_recommendation_tags": "cryogenic; freezers; biobanking", "workflow_examples": "Sample preservation, biobank management", "procurement_priority": "High", "approval_status": "Review", "is_preferred": True, "website": "https://www.thermofisher.com/cold-storage", "internal_notes": "Leader in cold storage", "budget_tier": "Premium", "country_region": "Global"},
    {"supplier_id": "SUP-046", "category": "Clinical, Hospital & Lab Supply Companies", "subcategory": "Safety and PPE", "company": "Kimberly-Clark Professional", "description": "Lab safety and PPE", "market_segment": "Both", "research_use": True, "clinical_use": True, "primary_offerings": "Gloves; lab coats; safety gear", "common_applications": "Lab safety, cleanroom, PPE", "ai_recommendation_tags": "PPE; gloves; safety gear", "workflow_examples": "Lab safety compliance", "procurement_priority": "Medium", "approval_status": "Review", "is_preferred": False, "website": "https://www.kcprofessional.com", "internal_notes": "Safety essentials", "budget_tier": "Economy", "country_region": "Global"},
    {"supplier_id": "SUP-047", "category": "Clinical, Hospital & Lab Supply Companies", "subcategory": "Hospital supplies", "company": "McKesson Medical-Surgical", "description": "Medical and hospital supplies", "market_segment": "Clinical/Hospital only", "research_use": False, "clinical_use": True, "primary_offerings": "Medical supplies; hospital consumables", "common_applications": "Hospital supply chain, medical devices", "ai_recommendation_tags": "hospital supplies; medical devices", "workflow_examples": "Hospital procurement", "procurement_priority": "High", "approval_status": "Review", "is_preferred": False, "website": "https://www.mckesson.com", "internal_notes": "Major healthcare distributor", "budget_tier": "Mid-market", "country_region": "North America"},
    {"supplier_id": "SUP-048", "category": "Clinical, Hospital & Lab Supply Companies", "subcategory": "Lab furniture", "company": "Labconco", "description": "Lab furniture and fume hoods", "market_segment": "Both", "research_use": True, "clinical_use": True, "primary_offerings": "Fume hoods; biosafety cabinets; freeze dryers", "common_applications": "Lab setup, safety equipment, lyophilization", "ai_recommendation_tags": "fume hoods; biosafety cabinets; lab furniture", "workflow_examples": "Lab infrastructure, safety compliance", "procurement_priority": "Medium", "approval_status": "Review", "is_preferred": False, "website": "https://www.labconco.com", "internal_notes": "Lab infrastructure", "budget_tier": "Mid-market", "country_region": "North America"},
    {"supplier_id": "SUP-049", "category": "Clinical, Hospital & Lab Supply Companies", "subcategory": "Pipettes and tips", "company": "Rainin (Mettler Toledo)", "description": "Pipettes and liquid handling", "market_segment": "Both", "research_use": True, "clinical_use": True, "primary_offerings": "Pipettes; tips; liquid handling", "common_applications": "Sample handling, liquid transfer, automation", "ai_recommendation_tags": "pipettes; tips; liquid handling", "workflow_examples": "Sample processing, PCR setup", "procurement_priority": "High", "approval_status": "Review", "is_preferred": True, "website": "https://www.mt.com/rainin", "internal_notes": "Premium pipette brand", "budget_tier": "Mid-market", "country_region": "Global"},
    {"supplier_id": "SUP-050", "category": "Clinical, Hospital & Lab Supply Companies", "subcategory": "Glassware", "company": "DWK Life Sciences", "description": "Laboratory glassware", "market_segment": "Both", "research_use": True, "clinical_use": True, "primary_offerings": "Glassware; bottles; vials", "common_applications": "Sample storage, chemical handling, labware", "ai_recommendation_tags": "glassware; bottles; vials", "workflow_examples": "Chemical storage, sample handling", "procurement_priority": "Medium", "approval_status": "Review", "is_preferred": False, "website": "https://www.dwk.com", "internal_notes": "Lab essentials", "budget_tier": "Economy", "country_region": "Global"},
]


def seed_suppliers():
    """Seed suppliers into the database"""
    db = SessionLocal()
    try:
        # Check if suppliers already exist
        existing = db.query(Supplier).first()
        if existing:
            print(f"Suppliers already seeded. Found {db.query(Supplier).count()} suppliers.")
            return

        # Add all suppliers
        for data in SUPPLIERS_DATA:
            supplier = Supplier(**data)
            db.add(supplier)

        db.commit()
        print(f"Successfully seeded {len(SUPPLIERS_DATA)} suppliers!")

    except Exception as e:
        print(f"Error seeding suppliers: {e}")
        db.rollback()
    finally:
        db.close()


if __name__ == "__main__":
    seed_suppliers()
