import React, { useState, useEffect } from 'react';
import toast from 'react-hot-toast';

interface QRCodeGeneratorProps {
  data: string;
  size?: number;
  title?: string;
  showDownload?: boolean;
  onClose?: () => void;
}

/**
 * QR Code Generator Component
 * Generates QR codes using Google Charts API (free, no API key needed)
 * Can be used for samples, equipment, documents, etc.
 */
export function QRCodeGenerator({
  data,
  size = 200,
  title,
  showDownload = true,
  onClose,
}: QRCodeGeneratorProps) {
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(false);

  // Generate QR code URL using Google Charts API
  const qrUrl = `https://chart.googleapis.com/chart?cht=qr&chs=${size}x${size}&chl=${encodeURIComponent(data)}&choe=UTF-8`;

  const handleDownload = () => {
    const link = document.createElement('a');
    link.href = qrUrl;
    link.download = `qr-${title || 'code'}-${Date.now()}.png`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    toast.success('QR Code downloaded');
  };

  const handleCopyData = () => {
    navigator.clipboard.writeText(data);
    toast.success('Data copied to clipboard');
  };

  const handlePrint = () => {
    const printWindow = window.open('', '_blank');
    if (printWindow) {
      printWindow.document.write(`
        <!DOCTYPE html>
        <html>
        <head>
          <title>QR Code - ${title || 'LabOS'}</title>
          <style>
            body {
              font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
              display: flex;
              flex-direction: column;
              align-items: center;
              justify-content: center;
              min-height: 100vh;
              margin: 0;
              padding: 20px;
            }
            .qr-container {
              text-align: center;
              padding: 30px;
              border: 2px solid #ddd;
              border-radius: 16px;
            }
            h2 { margin: 0 0 20px; color: #1a4480; }
            img { margin: 20px 0; }
            .data {
              font-family: monospace;
              font-size: 14px;
              color: #666;
              word-break: break-all;
              max-width: 300px;
              margin: 10px auto;
            }
            .footer {
              margin-top: 20px;
              font-size: 12px;
              color: #888;
            }
          </style>
        </head>
        <body>
          <div class="qr-container">
            ${title ? `<h2>${title}</h2>` : ''}
            <img src="${qrUrl}" alt="QR Code" />
            <div class="data">${data}</div>
            <div class="footer">Generated by LabOS v2 - ${new Date().toLocaleString()}</div>
          </div>
        </body>
        </html>
      `);
      printWindow.document.close();
      printWindow.print();
    }
  };

  return (
    <div style={{
      background: 'var(--surface)',
      borderRadius: 16,
      padding: 24,
      textAlign: 'center',
      border: '1px solid var(--border)',
    }}>
      {title && (
        <h3 style={{ fontSize: 16, fontWeight: 600, color: 'var(--text)', margin: '0 0 16px' }}>
          {title}
        </h3>
      )}

      <div style={{
        background: '#fff',
        borderRadius: 12,
        padding: 16,
        display: 'inline-block',
        marginBottom: 16,
      }}>
        {loading && !error && (
          <div style={{ width: size, height: size, display: 'flex', alignItems: 'center', justifyContent: 'center', color: 'var(--text-muted)' }}>
            Loading...
          </div>
        )}
        {error && (
          <div style={{ width: size, height: size, display: 'flex', alignItems: 'center', justifyContent: 'center', color: '#ef4444', fontSize: 14 }}>
            Failed to generate QR code
          </div>
        )}
        <img
          src={qrUrl}
          alt="QR Code"
          width={size}
          height={size}
          style={{ display: loading || error ? 'none' : 'block' }}
          onLoad={() => setLoading(false)}
          onError={() => { setLoading(false); setError(true); }}
        />
      </div>

      <div style={{
        background: 'var(--surface2)',
        borderRadius: 8,
        padding: 12,
        marginBottom: 16,
        wordBreak: 'break-all',
        fontFamily: 'monospace',
        fontSize: 12,
        color: 'var(--text-muted)',
      }}>
        {data}
      </div>

      {showDownload && (
        <div style={{ display: 'flex', gap: 8, justifyContent: 'center', flexWrap: 'wrap' }}>
          <button onClick={handleDownload} className="btn btn-primary" style={{ padding: '10px 16px', fontSize: 13 }}>
            Download PNG
          </button>
          <button onClick={handlePrint} className="btn btn-secondary" style={{ padding: '10px 16px', fontSize: 13 }}>
            Print
          </button>
          <button onClick={handleCopyData} className="btn btn-secondary" style={{ padding: '10px 16px', fontSize: 13 }}>
            Copy Data
          </button>
          {onClose && (
            <button onClick={onClose} className="btn btn-secondary" style={{ padding: '10px 16px', fontSize: 13 }}>
              Close
            </button>
          )}
        </div>
      )}
    </div>
  );
}

/**
 * QR Code Modal Component
 * Displays QR code in a modal overlay
 */
interface QRCodeModalProps {
  isOpen: boolean;
  onClose: () => void;
  data: string;
  title?: string;
  subtitle?: string;
}

export function QRCodeModal({ isOpen, onClose, data, title, subtitle }: QRCodeModalProps) {
  if (!isOpen) return null;

  return (
    <div style={{
      position: 'fixed',
      inset: 0,
      background: 'rgba(0,0,0,0.6)',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      zIndex: 1000,
      padding: 20,
    }}>
      <div style={{
        background: 'var(--surface)',
        borderRadius: 16,
        width: '100%',
        maxWidth: 400,
        padding: 24,
      }}>
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: 16 }}>
          <div>
            <h2 style={{ fontSize: 18, fontWeight: 700, color: 'var(--text)', margin: 0 }}>{title || 'QR Code'}</h2>
            {subtitle && <p style={{ color: 'var(--text-muted)', margin: '4px 0 0', fontSize: 14 }}>{subtitle}</p>}
          </div>
          <button onClick={onClose} style={{ background: 'none', border: 'none', fontSize: 24, color: 'var(--text-muted)', cursor: 'pointer' }}>x</button>
        </div>

        <QRCodeGenerator data={data} title={title} onClose={onClose} />
      </div>
    </div>
  );
}

/**
 * Batch QR Code Generator
 * Generates multiple QR codes at once
 */
interface BatchQRItem {
  id: string;
  data: string;
  label: string;
}

interface BatchQRCodeGeneratorProps {
  items: BatchQRItem[];
  onClose?: () => void;
}

export function BatchQRCodeGenerator({ items, onClose }: BatchQRCodeGeneratorProps) {
  const handlePrintAll = () => {
    const printWindow = window.open('', '_blank');
    if (printWindow) {
      const qrHtml = items.map(item => {
        const qrUrl = `https://chart.googleapis.com/chart?cht=qr&chs=150x150&chl=${encodeURIComponent(item.data)}&choe=UTF-8`;
        return `
          <div class="qr-item">
            <img src="${qrUrl}" alt="QR Code" />
            <div class="label">${item.label}</div>
            <div class="id">${item.id}</div>
          </div>
        `;
      }).join('');

      printWindow.document.write(`
        <!DOCTYPE html>
        <html>
        <head>
          <title>QR Codes - LabOS</title>
          <style>
            body {
              font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
              margin: 0;
              padding: 20px;
            }
            h1 { text-align: center; color: #1a4480; }
            .grid {
              display: grid;
              grid-template-columns: repeat(auto-fill, minmax(180px, 1fr));
              gap: 20px;
              margin-top: 20px;
            }
            .qr-item {
              text-align: center;
              padding: 16px;
              border: 1px solid #ddd;
              border-radius: 8px;
              page-break-inside: avoid;
            }
            .label { font-weight: 600; margin-top: 8px; font-size: 14px; }
            .id { font-family: monospace; font-size: 12px; color: #666; }
          </style>
        </head>
        <body>
          <h1>LabOS QR Codes</h1>
          <div class="grid">${qrHtml}</div>
        </body>
        </html>
      `);
      printWindow.document.close();
      printWindow.print();
    }
    toast.success(`Generated ${items.length} QR codes for printing`);
  };

  return (
    <div style={{ background: 'var(--surface)', borderRadius: 16, padding: 24, border: '1px solid var(--border)' }}>
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 20 }}>
        <h3 style={{ fontSize: 18, fontWeight: 600, color: 'var(--text)', margin: 0 }}>
          Batch QR Codes ({items.length} items)
        </h3>
        <div style={{ display: 'flex', gap: 8 }}>
          <button onClick={handlePrintAll} className="btn btn-primary" style={{ padding: '10px 16px', fontSize: 13 }}>
            Print All
          </button>
          {onClose && (
            <button onClick={onClose} className="btn btn-secondary" style={{ padding: '10px 16px', fontSize: 13 }}>
              Close
            </button>
          )}
        </div>
      </div>

      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(160px, 1fr))', gap: 16, maxHeight: 400, overflow: 'auto' }}>
        {items.map(item => {
          const qrUrl = `https://chart.googleapis.com/chart?cht=qr&chs=100x100&chl=${encodeURIComponent(item.data)}&choe=UTF-8`;
          return (
            <div key={item.id} style={{ background: '#fff', borderRadius: 8, padding: 12, textAlign: 'center' }}>
              <img src={qrUrl} alt="QR Code" width={100} height={100} />
              <div style={{ fontWeight: 600, color: '#1a1a1a', fontSize: 12, marginTop: 8 }}>{item.label}</div>
              <div style={{ fontFamily: 'monospace', fontSize: 10, color: '#666' }}>{item.id}</div>
            </div>
          );
        })}
      </div>
    </div>
  );
}

export default QRCodeGenerator;
