"""Admin endpoints for database migration management."""

from fastapi import APIRouter, HTTPException
from pydantic import BaseModel
from typing import Optional

from app.core import migrations as mig

router = APIRouter(prefix="/admin/migrations", tags=["admin-migrations"])


class UpgradeRequest(BaseModel):
    target: str = "head"


class DowngradeRequest(BaseModel):
    target: str = "-1"


class StampRequest(BaseModel):
    revision: str


class CreateRevisionRequest(BaseModel):
    message: str
    autogenerate: bool = False


@router.get("")
def get_migration_status():
    """Full migration status: current revision, head, pending count, history."""
    try:
        return mig.get_status()
    except Exception as exc:
        raise HTTPException(status_code=500, detail=str(exc))


@router.post("/upgrade")
def run_upgrade(body: UpgradeRequest = UpgradeRequest()):
    """Apply pending migrations up to target (default: head)."""
    result = mig.upgrade(body.target)
    if not result["success"]:
        raise HTTPException(status_code=500, detail=result.get("error", "Upgrade failed"))
    return result


@router.post("/downgrade")
def run_downgrade(body: DowngradeRequest = DowngradeRequest()):
    """Roll back migrations to target (default: -1 = one step back)."""
    result = mig.downgrade(body.target)
    if not result["success"]:
        raise HTTPException(status_code=500, detail=result.get("error", "Downgrade failed"))
    return result


@router.post("/stamp/{revision}")
def run_stamp(revision: str):
    """Mark DB at revision without running SQL (for bootstrapping existing DBs)."""
    result = mig.stamp(revision)
    if not result["success"]:
        raise HTTPException(status_code=500, detail=result.get("error", "Stamp failed"))
    return result


@router.post("/create")
def create_migration(body: CreateRevisionRequest):
    """Generate a new migration file, optionally with autogenerated diff."""
    result = mig.create_revision(body.message, body.autogenerate)
    if not result["success"]:
        raise HTTPException(status_code=500, detail=result.get("error", "Create failed"))
    return result


@router.get("/history")
def get_history():
    """List all revisions with applied/pending status."""
    try:
        return {"history": mig.get_history()}
    except Exception as exc:
        raise HTTPException(status_code=500, detail=str(exc))
